import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Nav from '@/stories/Nav';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400'],
	fallback: ['sans-serif'],
});

export const metadata: Metadata = {
	title: 'Aiko',
	description: 'Generated by create next app',
	robots: 'index, follow',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${poppins.className} antialiased`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
