import { Poppins } from 'next/font/google';
import Footer from '@/stories/Footer';
import Nav from '@/stories/Nav';
import './globals.css';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400'],
	fallback: ['sans-serif'],
});

export const metadata = {
	title: 'Aiko | Home',
	description: 'Generated by create next app',
	robots: 'index, follow',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${poppins.className} antialiased`}>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
